inherit_from: .rubocop_todo.yml

AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.4
  Exclude:
    - "bin/*"
    - Capfile
    - config/boot.rb
    - config/environment.rb
    - config/initializers/version.rb
    - db/schema.rb
    - "tmp/**/*"
    - Gemfile
    - Guardfile
    - Rakefile
    - db/migrate/*

# Metrics/AbcSize:
#   Exclude:
#     - "test/**/*"

# Metrics/BlockLength:
#   Exclude:
#     - "config/**/*"
#     - "test/**/*"

# Metrics/ClassLength:
#   Exclude:
#     - "test/**/*"

# Metrics/LineLength:
#   Exclude:
#     - "config/**/*"
#     - "db/**/*"

# Metrics/MethodLength:
#   Exclude:
#     - "db/migrate/*"
#     - "test/**/*"

Performance/Casecmp:
  Enabled: false

Rails:
  Enabled: true

Rails/Validation:
  Enabled: false

Style/BarePercentLiterals:
  EnforcedStyle: percent_q

Style/ClassAndModuleChildren:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/EmptyMethod:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/EndOfLine:
  EnforcedStyle: lf

Style/TrivialAccessors:
  AllowPredicates: true

Naming/VariableNumber:
  Enabled: false
