packages:
  - '.' # pins package discovery to the root only, avoiding the default recursive

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  core-js-pure: true

# The minimum age of a release to be considered for dependency installation.
# The value is in minutes (1440 minutes = 1 day).
minimumReleaseAge: 1440
