# ai bots: https://github.com/ai-robots-txt/ai.robots.txt/blob/main/robots.txt

- 360Spider
- ADmantX
- AI2Bot
- Ai2Bot-Dolma
- Amazonbot
- Applebot
- Applebot-Extended
- BLEXBot
- Baiduspider
- Bytespider
- CCBot
- ChatGPT-User
- Claude-Web
- ClaudeBot
- Diffbot
- DuckAssistBot
- FacebookBot
- FriendlyCrawler
- GPTBot
- Google-Extended
- GoogleOther
- GoogleOther-Image
- GoogleOther-Video
- ICC-Crawler
- ISSCyberRiskCrawler
- ImagesiftBot
- Kangaroo Bot
- MJ12bot
- Mail.RU_Bot
- MegaIndex
- Meta-ExternalAgent
- Meta-ExternalFetcher
- OAI-SearchBot
- PanguBot
- PerplexityBot
- PetalBot
- Scrapy
- Seekport Crawler
- Sidetrade indexer bot
- Sogou inst spider
- Sogou web spider
- Timpibot
- VelenPublicWebCrawler
- Webzio-Extended
- Yisouspider
- YouBot
- anthropic-ai
- cohere-ai
- dotbot
- iaskspider/2.0
- img2dataset
- omgili
- omgilibot
- proximic
- psbot
