- psbot
- PetalBot
- Mail.RU_Bot
- MegaIndex
- Baiduspider
- 360Spider
- Yisouspider
- Bytespider
- Sogou web spider
- Sogou inst spider
- proximic
- ADmantX
- Seekport Crawler
- BLEXBot
- MJ12bot
- dotbot
- GPTBot
- ChatGPT-User
- CCBot
- ChatGPT-User
- Claude-Web
- ClaudeBot
- cohere-ai
- Diffbot
- DuckAssistBot
- FacebookBot
- FriendlyCrawler
- Google-Extended
- GoogleOther
- GoogleOther-Image
- GoogleOther-Video
- GPTBot
- iaskspider/2.0
- ICC-Crawler
- ImagesiftBot
- img2dataset
- ISSCyberRiskCrawler
- Kangaroo Bot
- Meta-ExternalAgent
- Meta-ExternalFetcher
- OAI-SearchBot
- omgili
- omgilibot
- PanguBot
- PerplexityBot
- PetalBot
- Scrapy
- Sidetrade indexer bot
- Timpibot
- VelenPublicWebCrawler
- Webzio-Extended
- YouBot