name: docker
on:
  push:
    branches:
      - "development"
      - "master"

jobs:
  docker:
    name: Build & Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push app
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          target: app-dev
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_REPOSITORY }}:latest-app
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_REPOSITORY }}:latest-app
          cache-to: type=inline

      - name: Build and push worker
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./docker/Dockerfile
          target: worker-dev
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ vars.DOCKERHUB_REPOSITORY }}:latest-worker
          cache-from: type=registry,ref=${{ vars.DOCKERHUB_REPOSITORY }}:latest-worker
          cache-to: type=inline

      - name: Update description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: ${{ vars.DOCKERHUB_REPOSITORY }}
